### ISSUE TITLE
Where is the link to the second version? Could you please provide it? I'm really keen to take a look.

### ISSUE THREAD

**Issue by pedrogao** [ept/ddia2-feedback#1]

**Comment by ept** [comment]
Hi @pedrogao, you're quick to find this repo! It's not available yet – we are planning to put out an early release of the first few chapters in a couple of weeks. I just created the repo so that we can put the URL in the early release.

**Comment by ept** [comment]
The early release is now available here: https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/
