### ISSUE TITLE
missing word in chapter 1

### ISSUE THREAD

**Issue by yogabonito** [ept/ddia2-feedback#11]
A great first chapter so far! :clap: :clap:
I noticed a missing word. Instead of 'The term “serverless” can misleading' it should probably be 'The term “serverless” can be misleading'.
Keep up the awesome work! :raised_hands:

**Comment by yogabonito** [comment]
...also I am not sure what is meant by "arranged in Clos topologies". Could this be a typo? (Should it, for instance, be "close" instead of "Clos"?)

**Comment by yogabonito** [comment]
...also, "personal data many only be collected" should be "personal data may only be collected".

**Comment by dfasoro** [comment]
> ...also I am not sure what is meant by "arranged in Clos topologies". Could this be a typo? (Should it, for instance, be "close" instead of "Clos"?)

@yogabonito I was also unfamiliar with the term, I googled it and found resources on it e.g. https://docs.nvidia.com/networking-ethernet-software/guides/EVPN-Network-Reference/Introduction/#common-data-center-architectures

**Comment by ept** [comment]
Thanks, we'll fix the typos.

see here: https://en.wikipedia.org/wiki/Clos_network
