### ISSUE TITLE
`be` missing

### ISSUE THREAD

**Issue by abdullahfouad** [ept/ddia2-feedback#13]
https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch01.html#:-:text=can

**Comment by ept** [comment]
Hi @abdullahfouad, could you please quote the whole sentence where this occurs? There are many occurrences of the word "can" in Chapter 1.

**Comment by navidcs** [comment]
I went through all 98 instances of "can" in chapter one, but I couldn't find any that needs "be"; Maybe it's already fixed and I wasted my time :)

**Comment by ept** [comment]
Okay, thanks for checking :)
