### ISSUE TITLE
Chapter 2: Average, Median, and Percentiles [propose a ref on why mean are useful/useless]

### ISSUE THREAD

**Issue by mpalriwal-Netflix** [ept/ddia2-feedback#14]
I just finished reading the first chapter, and it resonates with the same simplicity as the first edition. The second chapter includes many references to my all-time favorite blogs by Mark and David from the Amazon Builders Library.

Additionally, I would like to suggest adding a reference to one of Mark's blogs, which can be found [here](https://brooker.co.za/blog/2017/12/28/mean.html). This blog shares a similar context regarding the use of the mean as a statistic.

https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#:-:text=However%2C%20the%20mean,experienced%20that%20delay.

**Comment by ept** [comment]
Good point that the mean has some valid uses. I'll add a reference to that blog post. Thanks!
