### ISSUE TITLE
Chapter 2 | Figure 2-3 | Proposal to introduce evolution of IO models and their pattern on Throughput vs Latency 

### ISSUE THREAD

**Issue by mpalriwal-Netflix** [ept/ddia2-feedback#16]
[BookLink](https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#:-:text=There%20is%20often%20a%20connection%20between%20throughput%20and%20response%20time%3B%20an%20example%20of%20such%20a%20relationship%20for%20an%20online%20service%20is%20sketched%20in%20Figure%C2%A02-3.%20The%20service%20has%20a%20low%20response%20time%20when%20request%20throughput%20is%20low%2C%20but%20response%20time%20increases%20as%20load%20increases.%20This%20is%20because%20of%20queueing%3A%20when%20a%20request%20arrives%20on%20a%20highly%20loaded%20system%2C%20it%E2%80%99s%20likely%20that%20the%20CPU%20is%20already%20in%20the%20process%20of%20handling%20an%20earlier%20request%2C%20and%20therefore%20the%20incoming%20request%20needs%20to%20wait%20until%20the%20earlier%20request%20has%20been%20completed.%20As%20throughput%20approaches%20the%20maximum%20that%20the%20hardware%20can%20handle%2C%20queueing%20delays%20increase%20sharply.)

> To enhance the understanding of the relationship between throughput and response time, it would be beneficial to consider the evolution of I/O models: Blocking I/O (BIO), Non-blocking I/O (NIO), and Asynchronous I/O (AIO).

* Blocking I/O (BIO): Typically results in higher response times as throughput increases due to its sequential processing nature, leading to significant queueing delays.
* Non-blocking I/O (NIO): Offers moderate improvements by allowing other operations to proceed while waiting for I/O, reducing queueing delays compared to BIO.
* Asynchronous I/O (AIO): Provides the most efficient handling of high loads, as it processes I/O operations in the background, minimizing response time even as throughput approaches maximum capacity.

Incorporating these models into the discussion can provide a clearer picture of how different I/O strategies impact system performance under varying loads.

##### The same is being discussed in one of my InfoQ article https://www.infoq.com/articles/reactive-java-vertx-deep-dive/

Blocking I/O (BIO):  the steepest curve.
Non-blocking I/O (NIO): the moderately rising curve.
Asynchronous I/O (AIO):  near the flattest curve.
![NIO_BIO_AIO](https://github.com/user-attachments/assets/04a3e440-596c-4b42-a7c1-e7b42e385fc9)

**Comment by ept** [comment]
I'm unclear about the distinction between non-blocking and asynchronous I/O – in my mind these two are equivalent (the calling thread does not wait for I/O to complete, but rather picks up the response later via an event loop that perhaps dispatches a callback). The article you link to doesn't really explain the distinction either. Could you elaborate?

**Comment by mpalriwal-Netflix** [comment]
Thank you for your feedback, Martin. I understand the confusion, as non-blocking and asynchronous I/O are often used interchangeably, but there are subtle differences captured here in an IBM recent [blog](https://developer.ibm.com/tutorials/j-nio/#networking-and-asynchronous-i-o57) : 

- **[Non-blocking or New I/O (NIO)](https://developer.ibm.com/tutorials/j-nio/#integrated-i-o5)**: In this model, I/O operations return immediately without waiting for data. The calling thread can continue executing other tasks and periodically check if the I/O operation is complete. This architecture encompasses two main components: ``Buffer & Channel``.

- **[Asynchronous I/O (AIO)](https://developer.ibm.com/tutorials/j-nio/#networking-and-asynchronous-i-o57)**: AIO extends NIO's capabilities by introducing an asynchronous, non-blocking model that uses callbacks to handle operations. . The calling thread doesn't need to check the status, as the system handles the completion notification. The central object in asynchronous I/O is called the ``Selector``. A Selector is where you register your interest in various I/O events


Key Differences

- ``Blocking``: NIO can be non-blocking, but AIO is inherently asynchronous, meaning it doesn't block at all.
- ``Notification``: NIO may require polling or checking for completion, while AIO uses callbacks or events for notification.
- ``Complexity``: AIO can be more complex to implement due to its asynchronous nature but offers greater efficiency for high-load scenarios.


I hope this clarifies the distinction. If you have further questions, I'd be happy to elaborate.

---

**Comment by mpalriwal-Netflix** [comment]
To add a recent news around this topic, similar to a multi-reactor pattern I've shared [here](https://www.infoq.com/articles/reactive-java-vertx-deep-dive/) 

> With intelligent multi-core utilization [and asynchronous I/O threading boost throughput to 1.2 million requests per second](https://valkey.io/blog/unlock-one-million-rps-part2/?utm_source=opensourcewatch.beehiiv.com&utm_medium=referral&utm_campaign=valkey-8-sets-a-new-bar-for-open-source-in-memory-nosql-data-storage), tripling the performance of previous versions. By switching from Redis's archaic single-thread event loop threading model to a sophisticated, I/O operations multithreaded approach, Valkey has vastly increased its speed.

**Comment by ept** [comment]
I'm still confused. The IBM blog post is very Java-specific, and it's still not clear to me what the fundamental (language-independent) difference is here. Language-specific design concerns and differences in APIs are not in scope for this book, as we're aiming for the big picture that applies to all systems regardless of language or platform. The valkey blog post seems to be about CPU/memory access optimisations and not about I/O at all – why is it relevant?

**Comment by mpalriwal-Netflix** [comment]
Thank you for your feedback, @ept . I understand the need to focus on language-independent concepts for the book. It can be relevant for readers to understanding how different I/O strategies impact system performance under varying loads.

I appreciate your focus on the big picture and am happy to refine the proposal to better align with the book's scope. Let me know if there's a way to integrate these concepts more effectively.

**Comment by ept** [comment]
Closing this issue as I don't think it makes sense to integrate this topic.
