### ISSUE TITLE
Chapter 2 : Average, Median, and Percentiles | Proposal to share context around Trimmed Mean 

### ISSUE THREAD

**Issue by mpalriwal-Netflix** [ept/ddia2-feedback#17]
[BookLink](https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#:-:text=Average%2C%20Median%2C%20and%20Percentiles)

``Feedback`` : I want to propose adding a new section under ``Average, Median, and Percentiles`` to share more about ``Trimmed mean``  and its importance over percentile. 

--------
The ``Trimmed mean``  has become a popular statistic for measuring latency duration, offering an alternative to using the ``average or percentiles``. 

By excluding a certain percentage of the highest and lowest values, the trimmed mean provides a more accurate representation of typical performance, minimizing the impact of outliers.

This approach helps in understanding latency behavior more effectively, ensuring a balanced view of system performance without being skewed by extreme values.

> ##### As shared in one of my Infoq article https://www.infoq.com/articles/aws-lambda-cold-starts-myths/ 

* Outliers skew averages, so the average doesn’t represent typical behavior in a system with outliers.
* Percentile(p) and TrimmedMean(tm) are good ways to define a service API latency goal.
* p99 represents the worst (highest latency) experience for 99% of our customers’ requests. It does not tell us what percentage of those 99% requests observed the worst experience (highest latency).
tm99 represents the mean of the 99% of our customers’ requests that have been trimmed (by removing 1% outliers).
* A higher TrimmedMean(tm) indicates a higher frequency of outliers, while a higher percentile(p) mainly indicates the highest duration of outlier.
* A higher TrimmedMean(tm) is more concerning than a higher percentile(p) as it means a significant % of customers are seeing an elevated latency.

<img width="590" alt="Screenshot 2024-10-10 at 3 02 17 AM" src="https://github.com/user-attachments/assets/f378f7f8-7c2e-48e2-9542-0240217915f7">

**Comment by ept** [comment]
I think including trimmed means in the discussion may go into a bit more depth than what we really need for this chapter. Remember the purpose of the book is to give a quick, cursory overview of a large number of topics that are likely to be important for a large number of people working on data systems – so we want to keep it as short as possible. I would argue that percentiles are essential to understand, whereas if we go into trimmed means (which, as far as I can tell, are much less widely used) we'll also need a discussion of how they differ from percentiles, and I feel that's probably too much detail for this book. What do you think @criccomini?

**Comment by mpalriwal-Netflix** [comment]
@ept, I appreciate your focus on keeping the content concise. However, I believe including a brief mention of the trimmed mean could significantly benefit the audience. As Jim explains in [this video](https://youtu.be/_uaaCiyJCFA?feature=shared&t=640), the trimmed mean provides a robust alternative for understanding latency by minimizing the impact of outliers.

While percentiles are essential, the trimmed mean offers a complementary perspective that can be particularly useful in scenarios with frequent outliers. A short section could highlight its practical applications without delving into complex details, thus enriching the reader's toolkit for analyzing data systems.

This addition could empower readers to make more informed decisions in environments where outliers significantly affect performance, aligning with the book's goal of providing valuable insights for a wide range of data professionals.

As I've shared in my InfoQ article on [Lambda Cold Start Myths](https://www.infoq.com/articles/aws-lambda-cold-starts-myths/), the trimmed mean is crucial for measuring function latency versus percentiles. If the trimmed mean changes while the percentile remains the same, it indicates a shift in the frequency of outliers (cold starts).

For example, in "Scenario A," p100 is 1100ms, while in "Scenario B," p100 is 600ms. Determining which is better is challenging, but the trimmed mean provides that clarity.

**Comment by ept** [comment]
There are many, many ways in which the book could be extended, and no doubt those extensions would be valuable to some of our readers. But at some point we have to draw a line between what is essential and what is optional, and that is to some extent a subjective/editorial decision. I still think that percentiles are essential to understand, but a trimmed mean is not, and this addition would not be worth the added complexity in a book that's already too long. Nevertheless, thank you for your feedback!
