### ISSUE TITLE
Chapter 2 | Fix typo "wth"

### ISSUE THREAD

**Issue by duonghan** [ept/ddia2-feedback#18]
[Link](https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#:-:text=if%20you%20cannot,the%20new%20one%2C)

> One major factor that makes change difficult in large systems is when some action is irreversible, and therefore that action needs to be taken very carefully [[90](https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#Zaninotto2002)]. For example, say you are migrating from one database to another: if you cannot switch back to the old system in case of problems **wth** the new one, the stakes are much higher than if you can easily go back. Minimizing irreversibility improves flexibility.

**Comment by ept** [comment]
Will be fixed in the next update. Thanks!
