### ISSUE TITLE
Chapter 1: Microservices and Serverless 

### ISSUE THREAD

**Issue by mpalriwal-Netflix** [ept/ddia2-feedback#19]
[BookLink](https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch01.html#:-:text=Serverless%2C%20or%20function,resources%20in%20advance.)

1) 
I really value the comprehensive overview of ``microservices and serverless`` architectures in this section. To further enrich the discussion, it might be helpful to explore some of the potential [downsides or challenges](https://brainhub.eu/library/disadvantages-of-serverless-computing) associated with serverless computing, similar to the balanced approach taken with microservices.

------
2)
Additionally, while discussing serverless, it could be valuable to mention that the term extends beyond  ``FaaS`` to include other services like serverless ``storage, queues, databases``, and ``compute options beyond FaaS``. This broader perspective could provide readers with a more complete understanding of the serverless paradigm.

> Serverless, or function-as-a-service (FaaS), is another approach to deploying services, in which the management of the infrastructure is outsourced to a cloud vendor.

**Comment by criccomini** [comment]
Thanks! I've updated ch1 with some extra notes on the tradeoffs with serverless. I've also clarified that some infra such as BigQuery and Kafka vendors use the term "serverless" to signal that there is no cluster, and resources are managed by usage instead.

**Comment by mpalriwal-Netflix** [comment]
Thank you @criccomini for considering my suggestion and incorporating it into the book!
