### ISSUE TITLE
Here for the early release

### ISSUE THREAD

**Issue by fanyak** [ept/ddia2-feedback#2]
I would like to check out the early Release of the second edition of Designing Data-Intensive Applications

**Comment by criccomini** [comment]
Hi! The first 3 chapters are forthcoming. See this comment for more details:

https://github.com/ept/ddia2-feedback/issues/1#issuecomment-2293768209

**Comment by ept** [comment]
The early release is now available here: https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/
