### ISSUE TITLE
Chapter 2: Typo

### ISSUE THREAD

**Issue by jcbm** [ept/ddia2-feedback#21]
https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#sec_introduction_percentiles

In the Throughput part in the beginning of the linked section: 

`For a given a particular allocation of hardware resources, there is a maximum throughput that can be handled. The unit of measurement is “somethings per second”.`

Seems like it should be either "a given" or "a particular" here.

**Comment by ept** [comment]
Hi @jcbm, thanks for pointing this out. It'll be fixed in the next update.
