### ISSUE TITLE
Chapter 1: clarifying the role of data analysts vs. business analysts

### ISSUE THREAD

**Issue by Emekat** [ept/ddia2-feedback#22]
In Chapter 1, you describe "business analysts" as generating reports to help management make better decisions. However, this aligns more closely with the role of data analysts or BI analysts, who focus on working with data to create insights and reports.

In contrast, business analysts focus on understanding business needs, gathering requirements, and proposing solutions, which goes beyond the data-centric scope described in this chapter.  
While this description is accurate in a broad sense, I believe the term "business analyst" might not be the most precise fit in the context of this chapter. 

Based on the activities described—working with data to generate reports and aid decision-making—the role aligns more closely with that of a data analyst or BI (Business Intelligence) analyst rather than a business analyst

Using "data analyst" or "BI analyst" would provide better clarity for readers, as it accurately reflects their data-focused responsibilities.

I propose revising the sentence to:

"In addition to the teams managing backend services, two other groups of people typically require access to an organization’s data: data analysts, who generate reports about the organization’s activities to help management make better decisions, and data scientists..." 
This change ensures the terminology is precise and aligns with the book’s focus on data systems

**Comment by ept** [comment]
@criccomini You know better than me how things work in companies. What do you think?

**Comment by criccomini** [comment]
I think we're splitting hairs here. My experience is that these titles are not well defined, and different organizations will use different terms for the same thing. I've even seen some orgs deliberately mis-name their roles in order to attract more applicants and make hiring easier.

That said, I do feel that "business analyst" is a bit of a dated term. For this reason, I'd propose using "data analyst" since it seems to me to be a term that an unfamiliar will most be able to understand intuitively.

**Comment by Emekat** [comment]
thanks @criccomini and @ept

**Comment by criccomini** [comment]
Dug around a bit more. This is a more invasive change than I thought:

```
ch01-tradeoffs.asciidoc:((("business analyst")))
ch01-tradeoffs.asciidoc:access to an organization's data: _business analysts_, who generate reports about the activities of
ch01-tradeoffs.asciidoc:Although business analysts and data scientists tend to use different tools and operate in different
ch01-tradeoffs.asciidoc:  _Analytical systems_ serve the needs of business analysts and data scientists. They contain a
ch01-tradeoffs.asciidoc:Analytics engineers model and transform data to make it more useful for the business analysts and
ch01-tradeoffs.asciidoc:individual records to the user. For example, a business analyst at a supermarket chain may want to
ch01-tradeoffs.asciidoc:It is usually undesirable for business analysts and data scientists to directly query these OLTP
ch01-tradeoffs.asciidoc:other hand, an enterprise usually has a single data warehouse, so that business analysts can combine
ch01-tradeoffs.asciidoc:((("business analyst")))
ch01-tradeoffs.asciidoc:for the types of queries that business analysts need to make, but it is less well suited to the
ch03-datamodels.asciidoc:and _one big table_ (OBT). These structures are optimized for the needs of business analysts. ETL
ch11-batch.asciidoc:to graphical tools used by business analysts (such as Tableau).
```

Also, 

![Screenshot 2024-12-16 at 10 25 03 AM](https://github.com/user-attachments/assets/358bbef4-ae80-4a52-824b-2c21e34bf73c)

https://en.wikipedia.org/wiki/Business_analyst

> A business analyst (BA) is a person who processes, interprets and documents [business processes](https://en.wikipedia.org/wiki/Business_process), products, services and [software](https://en.wikipedia.org/wiki/Software) through analysis of [data](https://en.wikipedia.org/wiki/Data).

Given that I feel we're splitting hairs here, I'm going to leave things as-is. IMO, the juice isn't worth the squeeze.

**Comment by ept** [comment]
Ok, thank you @criccomini!
