### ISSUE TITLE
Possible broken link

### ISSUE THREAD

**Issue by sophist0** [ept/ddia2-feedback#23]
In chapter 1 the perma link for reference [https://perma.cc/3F5N-FUQ4](url) appears to be broken.

![Screenshot from 2024-12-23 10-02-37](https://github.com/user-attachments/assets/afbcd2a7-5ec8-4c14-aa55-69345936becb)

**Comment by sophist0** [comment]
Actually reloading the page seems to have fixed the error, so maybe it was a temporary issue.

**Comment by ept** [comment]
Thanks for your note. It seems like it was a temporary glitch that's now resolved.
