### ISSUE TITLE
Is December 2025 an optimistic or pessimistic release date estimate?

### ISSUE THREAD

**Issue by wilfreddesert** [ept/ddia2-feedback#4]
This is not really an issue per se, but I'm really curious whether there are chances the book will be ready earlier than the end of next year. 

The second question is what are the most significant changes compared to the first edition? If someone has read the first edition, roughly what will be the overlap? Honestly, I think I'm going to buy it immediately and then treat as a separate book, but it's still interesting whether it's a sequel with more advanced material or rather an update? 

Thank you!

**Comment by ept** [comment]
Hi @wilfreddesert:

1. We're hoping to wrap up the writing in the first half of next year, but then there are still technical reviews and production before it's released, so it's unlikely to happen much earlier.
2. It's very much an update of the existing book, not a sequel. The overall structure and topics remain pretty much the same; we're just adding a bit of stuff that has recently changed, and deleting some stuff that has become dated. If you've already read the first edition, you probably won't get a lot out of reading the second, unless you're curious about the details of how technology has changed in the last decade. But I'm hoping that for people reading it for the first time, the second edition will be better all-around.
