### ISSUE TITLE
typos in chap 01?

### ISSUE THREAD

**Issue by guojilin80** [ept/ddia2-feedback#6]
1. in section 'Data Warehousing' 

"A large enterprise may have dozens, even hundreds, of operational transaction processing systems"
-> (emit "transaction processing")
"A large enterprise may have dozens, even hundreds, of operational systems"

2. in section 'Data Systems, Law, and Society' 

"personal data many only be collected for a specified, explicit purpose"
->( "many" should be "may")
"personal data may only be collected for a specified, explicit purpose"

pls check, tks!

**Comment by guojilin80** [comment]
'emit' should be 'omit' -__-

**Comment by criccomini** [comment]
Thanks for these! I'm updating as you submit them. 🙂
