### ISSUE TITLE
How to draw sequence diagrams like this

### ISSUE THREAD

**Issue by dnxbjyj** [ept/ddia2-feedback#7]
I found many diagrams like this in book：
![image](https://github.com/user-attachments/assets/d2097ed3-fde2-4e9d-929d-c6e271c77a47)

I feel these diagrams are very useful in my work, what's name of this diagram? How to draw them? Is there any tools could be used? (eg. PlantUML）

Thank you!

**Comment by ept** [comment]
Hi @dnxbjyj, I draw the diagrams with a general-purpose vector graphics editor (Adobe Illustrator). I don't know if there is a specialised tool for drawing this type of diagrams.

**Comment by dnxbjyj** [comment]
I've got it，thank you very much！
