### ISSUE TITLE
a typo at the beginning of chapter 3 ?

### ISSUE THREAD

**Issue by guojilin97** [ept/ddia2-feedback#8]
at the beginning of chapter 3,  it seems that "XML data model" is not totally removed in the example : 

![image](https://github.com/user-attachments/assets/a9acd931-cc61-4256-b867-052927d69297)

**Comment by ept** [comment]
We're not removing XML – there are a couple of references to XML data in the chapter. We can change "JSON" to "document" in point 3 to clarify this.
